#ifndef CONTIKI_ARCH_PLATFORM_STM32LDISCO_RF230_STM32LDISCO_RF230_H_
#define CONTIKI_ARCH_PLATFORM_STM32LDISCO_RF230_STM32LDISCO_RF230_H_

typedef unsigned long clock_timer_t;

#define CLOCK_CONF_SECOND           128

#define RTIMER_ARCH_SECOND          32768

#define PLATFORM_HAS_LEDS           1
#define PLATFORM_HAS_BUTTON         1

#define NETSTACK_CONF_WITH_IPV6     1
#define NETSTACK_CONF_WITH_IPV4	    0
#define NETSTACK_CONF_WITH_RIME	    0

#define NETSTACK_CONF_RADIO         at86rf2xx_driver

#define STACK_CHECK_CONF_ENABLED    0

#endif /* CONTIKI_ARCH_PLATFORM_STM32LDISCO_RF230_STM32LDISCO_RF230_H_ */
