/*
 * board.h
 *
 *  Created on: Feb 20, 2018
 *      Author: jucom
 */

#ifndef CONTIKI_ARCH_PLATFORM_STM32LDISCO_RF230_DEV_BOARD_H_
#define CONTIKI_ARCH_PLATFORM_STM32LDISCO_RF230_DEV_BOARD_H_

#define BOARD_STRING "STM32L1-Discovery + AT86RF230"

#endif /* CONTIKI_ARCH_PLATFORM_STM32LDISCO_RF230_DEV_BOARD_H_ */
